apiVersion: apps/v1 
kind: Deployment
metadata:
  name: devops
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 1
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: devops
        name: devops
        image: maximiano86/devops
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devops
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: devops
            port:
              number: 80

#spec:
#  tls:
#  - hosts:
#      - dev-sloan.com
#    secretName: dev-sloan-ssl
#  rules:
#  - host: dev-sloan.com
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: devops
#            port:
#              number: 80         

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops
data:
  SAMPLE_VALUE: "THIS_IS_A_SAMPLE_VALUE"
  SECOND_VALUE: "SECOND_VALUE"